### ISSUE TITLE
关于NG-R8在OS X 10.11.6上失效

### ISSUE THREAD

**Issue by Suki-Tomie** [qinyuhang/ShadowsocksX-NG-R#1]
你好，很抱歉之前在NG那边直接@了你（第一次打开NG-R的时候没找到Issues(｡-_-｡)）

昨天在这里下载的最新版NG-R8在我的MAC上失效了。同样的SSR账号在安卓的SSR端连接正常。
用NG-R8上的服务器测速是可以测出ping的，但是浏览器并不能访问墙外：
  比如访问youtube
    Safari 用PAC代理是“Safari打不开页面”，用全局代理是“Safari不能连接到代理服务器”；
    Chrome 用PAC代理是“无法访问此站”，用全局代理是“无法访问此网站”。

求助－－T^T

**Comment by sweet2honey** [comment]
问题同样 求解 谢谢

**Comment by Esinchung** [comment]
auth_chain_b在10.11.6无法用，10.12可以

**Comment by Suki-Tomie** [comment]
auth_chain_b是什么？@Esinchung

**Comment by ghost** [comment]
> auth_chain_b是什么？@Esinchung

A new protocol.

**Comment by Suki-Tomie** [comment]
所以是因为10.11.6不支持这个新协议吗？  哦刚google到了，谢谢，谢谢大家的回答
