### ISSUE TITLE
用哪个公钥啊? 前面两个好像过期了耶，最后一个不能用。

### ISSUE THREAD

**Issue by wenxingxing** [qinyuhang/ShadowsocksX-NG-R#110]
![如图](https://i.imgur.com/oBOzPTI.png)

**Comment by zhengwu119** [comment]
+1

**Comment by BenjaminGao** [comment]
![snipaste_2018-12-19_19-18-52](https://user-images.githubusercontent.com/16028320/50217425-954f0280-03c3-11e9-8b33-05a007cdfca0.png)
![snipaste_2018-12-19_19-22-38](https://user-images.githubusercontent.com/16028320/50217428-97b15c80-03c3-11e9-9dd6-625a5f44030b.png)

**Comment by ohowen** [comment]
这是没人维护的吗

**Comment by BenjaminGao** [comment]
> 这是没人维护的吗

我看了下，今年不管哪个分支都没有更新过代码，应该是放弃维护了。

**Comment by wenxingxing** [comment]
用clash吧, close
