### ISSUE TITLE
建议更新ACL规则配置文件

### ISSUE THREAD

**Issue by nico-zck** [qinyuhang/ShadowsocksX-NG-R#119]
建议更新一下ACL的配置文件
目前已经有一个库在维护ACL规则了，手动更新的情况下，还挺好用的，希望能够集成更新功能
[ACL规则仓库](https://github.com/ACL4SSR/ACL4SSR)

**Comment by yimmy23** [comment]
想知道可以自己更行acl规则么？

**Comment by nico-zck** [comment]
acl文件默认位置在
> /Users/username/.ShadowsocksX-NG/

该目录下，其中`gfwlist.acl`是acl自动模式的文件；`chn.acl`是白名单模式文件；`backchn.acl`是acl代理大陆模式的文件，可以根据需要自行替换；


另外，我在使用过程中发现在ssr软件的高级设置中其实可以自定义更新规则的地址：
![image](https://user-images.githubusercontent.com/10665923/59325678-8b74df00-8d16-11e9-9ce3-69aad6b5d491.png)
在`代理规则`下，选择`更新gfw`和`更新全部白名单`即可根据填写的url立即更新规则文件。

**Comment by yimmy23** [comment]
十分感谢
