### ISSUE TITLE
如何在r8中自定pac文件或者下载地址？

### ISSUE THREAD

**Issue by EndangeredF1sh** [qinyuhang/ShadowsocksX-NG-R#17]
填入GFW LIST URL中无法更新自定PAC 在mac-网络下虽然可以设置，但是不想每次开完全局回到PAC自动的时候都被自动覆盖。
请问有解决方案吗？谢谢！

**Comment by itopinion** [comment]
同样有这个需求，目前的白名单模式有问题；我想自己用手动模式+自定义PAC文件；尝试用Mac自己做web server指定到pac文件，但是无效。。。
