### ISSUE TITLE
如何使用命令导入导出配置？

### ISSUE THREAD

**Issue by chyroc** [qinyuhang/ShadowsocksX-NG-R#19]
如题，我的应用场景就是感觉一条线路不佳的时候，执行一个脚本，自动去切换

对于 ShadowsocksX-NG ：
可以这样： https://github.com/shadowsocks/ShadowsocksX-NG/issues/168#issuecomment-269783544 ，然后配合我写的一些脚本可以实现

```
$ defaults export com.qiuyuzhou.ShadowsocksX-NG config.plist
$ plutil -convert json -o config.json config.plist
$ plutil -convert xml1 config.json -o config.plist
$ plutil config.plist
$ defaults import com.qiuyuzhou.ShadowsocksX-NG config.plist
```

对于本项目，可以怎么搞呢？

我试过把 `com.qiuyuzhou.ShadowsocksX-NG` 换成 `com.qinyuhang.ShadowsocksX-NG-R8` 或者 `com.qinyuhang.ShadowsocksX-NG-R` ，但是不行

**Comment by chyroc** [comment]
`clowwindy.ShadowsocksX.plist`，这个？

如果是的话，可以转成xml1格式，不能转成json格式？

**Comment by chyroc** [comment]
我知道了，位置是一样的。。

**Comment by twistfz** [comment]
我现在也是想实现这样的功能，改了plist是需要重启才能生效么？
