### ISSUE TITLE
成功订阅节点后,并没有真正的获取节点列表

### ISSUE THREAD

**Issue by wYuanHpp** [qinyuhang/ShadowsocksX-NG-R#2]
问题如标题,不知道是为什么

**Comment by Chandler-Lu** [comment]
要么你的订阅链接就有问题，也有可能你的列表里已经有了你订阅的节点

**Comment by qinyuhang** [comment]
may notrelated to incorrect diff. the incorrect diff problem is fixed

**Comment by leadscloud** [comment]
我的 mac 获取订阅成功，但服务器列表中还是为空。我把所有服务器删除仍然 有这问题。@Chandler-Lu  
那两个原因都不是。

猜测原因可以是缓存的问题，我把程序删除，再次安装服务器订阅默认就有了，我在别人的电脑安装，服务器订阅成功后服务器就是有的。

**Comment by fr0der1c** [comment]
+1 同样遇到此情况，提示获取成功，但是列表是空的。

**Comment by wells1013** [comment]
+1 同样遇到此情况

**Comment by leadscloud** [comment]
试用https，好像是http的不支持。
