### ISSUE TITLE
你跟breakwa11啥关系？这里的好像跟那边是一样的。

### ISSUE THREAD

**Issue by zh-chen** [qinyuhang/ShadowsocksX-NG-R#3]

**Comment by ghost** [comment]
This issue is not related to any bugs or enhancements, and you should get the answer from [hly928 's comment](https://github.com/shadowsocks/ShadowsocksX-NG/issues/462#issuecomment-323540850).

If you still want more details about these, I would recommend [Google](www.google.com) for you.
