### ISSUE TITLE
What is the format of the server subscription file?

### ISSUE THREAD

**Issue by paulgit** [qinyuhang/ShadowsocksX-NG-R#37]
Hi, I would like to use the server subscription option but I do not know what the format of the file should be. I have tried the exported JSON file but this does not appear to work.

Any help would be appreciated.

**Comment by ghost** [comment]
Hi, paulgit. 

The subscription file is encoded by base64, and you could ask your proxy provider if this opinion is available. (It should be a **https** URL, http subscription isn't supported yet.)

**Comment by paulgit** [comment]
Thanks for the reply, ok on the base64 encoding, but what is the format of the file prior to encoding?

**Comment by ghost** [comment]
Mine is *.conf, FYI.

**Comment by paulgit** [comment]
Ok, but inside the file is the contents JSON or just a list of SSR:// URLs?

**Comment by ghost** [comment]
The latter.

**Comment by paulgit** [comment]
Thank you!
