### ISSUE TITLE
无法检查更新

### ISSUE THREAD

**Issue by leewi9** [qinyuhang/ShadowsocksX-NG-R#38]
可能原来是把版本更新地址硬编码了，麻烦看下能不能改一下

**Comment by ghost** [comment]
https://github.com/qinyuhang/ShadowsocksX-NG-R/pull/32

This pull request already fixes it. Before it has been merged, you can go to https://github.com/qinyuhang/ShadowsocksX-NG-R/releases and check if a update is available.
