### ISSUE TITLE
请问实际使用的ACL保存在哪里？或如何判断ACL订阅更新了？

### ISSUE THREAD

**Issue by ernestyao** [qinyuhang/ShadowsocksX-NG-R#49]
ShadowsocksX-NG-R Version 1.4.3-R8 (2)
MacOS 10.13.1
安装后应用程序的包里有ACL文件。我自己修改了高级设置里面ACL的订阅地址，上网正常，但不知道ACL的订阅是否更新了。应用程序包里的文件日期还是上个月的，但ACL订阅地址的文件是近期修改的。

**Comment by ghost** [comment]
`~/.ShadowsocksX-NG/gfwlist.acl`

**Comment by ernestyao** [comment]
多谢楼上，已找到。
