### ISSUE TITLE
"Show network speed" doesn't work

### ISSUE THREAD

**Issue by wao1201** [qinyuhang/ShadowsocksX-NG-R#5]
App Version:
![SS](https://ws2.sinaimg.cn/large/006tKfTcgy1fiv088ct8sj30b008ndgj.jpg)

OS Version: macOS 10.12.6

**Comment by ghost** [comment]
Because macOS Sierra has removed sar, apps use this command to collect system statistics may not work correctly.

**Comment by wao1201** [comment]
OK, I see. Thanks for the comment.

**Comment by anticpc** [comment]
@ghost thx.
