### ISSUE TITLE
升10.3.2连不上了

### ISSUE THREAD

**Issue by kevin335200** [qinyuhang/ShadowsocksX-NG-R#60]
Closed.

**Comment by yangfeicheung** [comment]
我改的这个版本可以用哦，感兴趣的可以试试，多了些方便的小功能，比如屏蔽广告，高可用性模式，macOS 13.2也运行正常

https://github.com/yangfeicheung/Shadowsocks-X

**Comment by 1kevin335200** [comment]
@yangfeicheung 在等你的SSR支持😄 服务商只用SSR没办法

**Comment by juniorxxue** [comment]
same
