### ISSUE TITLE
关于跳过中国大陆IP

### ISSUE THREAD

**Issue by nehcnoel** [qinyuhang/ShadowsocksX-NG-R#66]
Hi support,
请问是什么原因取消了**跳过中国大陆IP**选项，感觉挺好用的呀。
有哪位大佬能提供含有此选项的版本，小弟万分感谢🙏。

**Comment by Chandler-Lu** [comment]
把acl白名单改成https://raw.githubusercontent.com/shadowsocksrr/shadowsocksX-NG-R-ACL/master/chn.acl，然后更新就行了

**Comment by nehcnoel** [comment]
@Chandler-Lu 解决了，多谢。
