### ISSUE TITLE
使用不了了

### ISSUE THREAD

**Issue by kiongweidong** [qinyuhang/ShadowsocksX-NG-R#75]
从上周二开始就突然用不了了，订阅的节点全部不能用，上谷歌的时候上不去然后就提示说是代理的问题就跑到设置-网络-高级-代理里面把所有打勾的选项都取消了，然后又可以用过了一段时间又不行了，然后一直到现在也是断断续续的，大部分时间还是使用不了

**Comment by yangfeicheung** [comment]
you can contact me if you have any issue

**Comment by itzhaclea** [comment]
Please contact your VPS provider, the problem is **not** related to this program.
