### ISSUE TITLE
macOS 10.9.5无法安装

### ISSUE THREAD

**Issue by JiaPeng89** [qinyuhang/ShadowsocksX-NG-R#79]
能否解决下？

**Comment by qinyuhang** [comment]
Running requirement: macOS 10.11 +

**Comment by JiaPeng89** [comment]
一些原因我不想升级系统，能否告知，哪里可以下载到10.9.5可以安装的shadowsocksr？ @qinyuhang

**Comment by yangfeicheung** [comment]
hey bro, this version supports that os

https://github.com/yangfeicheung/Shadowsocks-X

**Comment by JiaPeng89** [comment]
@yangfeicheung 太棒了！搞定了！谢谢！
