### ISSUE TITLE
“ssr://” 连接支持

### ISSUE THREAD

**Issue by YouZhengChuan** [qinyuhang/ShadowsocksX-NG-R#8]
能不能支持直接通过“ssr://”连接添加服务器呢？

**Comment by qinyuhang** [comment]
早已支持，你是要反应不可以（功能失效）？还是不知道可以呢？

**Comment by issuessss** [comment]
如何粘贴 ssr://链接地址? 比如我拷贝一个 ssr://地址,然后在 app 里面如何粘贴进去?

**Comment by qinyuhang** [comment]
粘贴到Safari 回车

发自我的 iPhone

**Comment by issuessss** [comment]
哦, 原来是这样搞. 我一直用的是 chrome, 粘贴到 chrome,就自动搜索了. 多谢
