### ISSUE TITLE
mac 无法正常使用ShadowsocksX-NG-R8

### ISSUE THREAD

**Issue by momuoy** [qinyuhang/ShadowsocksX-NG-R#89]
![1](https://user-images.githubusercontent.com/40311423/41634911-85d1ffd6-7478-11e8-860f-a24dc10295bd.jpeg)

wins上可以使用，Mac上一直用不了，忍无可忍来投个稿，希望得到解决谢谢

**Comment by qinyuhang** [comment]
Any useful information about cannot use it normally?

**Comment by momuoy** [comment]
windows上可以使用， mac上用不了。

**Comment by qinyuhang** [comment]
No useful information provided. I'm closing this issue.

**Comment by momuoy** [comment]
那我要提供什么有用的信息……您给个提示？
就用不了啊，什么网站都打不开，切换线路也打不开

**Comment by qinyuhang** [comment]
fill this form PLZ.
https://github.com/qinyuhang/ShadowsocksX-NG-R/blob/develop/ISSUE_TEMPLATE.md
