### ISSUE TITLE
http订阅仍是一个大缺点

### ISSUE THREAD

**Issue by liesauer** [qinyuhang/ShadowsocksX-NG-R#95]
如果是云服的话上https还好说，但是如果是虚机的话上https那就麻烦了，首先得要升级，然后才有独立IP，然后才能申请证书，中途可能还要花钱。所以http订阅真的很有必要啊
之所以关注这个版本的ssrng是因为有订阅！但是失望也是意料之中的失望是ATS的通病。望克服改进，致敬！

**Comment by Maecenas** [comment]
如果我的理解是对的话，现在的版本支持 HTTPS 的服务器订阅（也是我发现唯一支持订阅的 SSR 客户端），但是不支持 HTTP 的服务器订阅。

试一下 [Let's Encrypt](https://letsencrypt.org/) (或者是 [certbot](https://certbot.eff.org/)) 上 HTTPS。[`acme.sh`](https://github.com/Neilpang/acme.sh) 在这基础上简化了自动更新证书的配置。

**Comment by liesauer** [comment]
@Maecenas 目前我的订阅是虚拟主机做的，不是服务器，所以我要上https的话要给虚机买一个独立ip，而且我那坑爹的提供商部署ssl居然收费，真是无语

**Comment by Maecenas** [comment]
VPS 服务提供商不给公网 IP 的话比较坑。总可以共享实体机网卡的 IP，通过端口划分服务吧。证书下发收费讲得通，而且赛门铁克/TrustAsia 都有免费的证书。不知道 SSL 部署怎么收费呢，用 Nginx 转发一下也不行吗？
